### PR TITLE
Add Gradle and Bintray (Maven) support

### PR DESCRIPTION
**Pull request by Guardiola31337**
- Adds Gradle and Bintray (Maven) support

The code now is under a new module called `artifact`.

@macroing could you check 👇?

- [ ] Previous mechanism to build the project (Ant) is still working
- [ ] GUI client is still working. Is there any absolute path pointing to `Evaluate.png`? If so, we should fix it.

After merging this PR I can guide you on how to create a [Bintray account](https://bintray.com/signup/oss) and how to upload the artifact to Bintray and Maven Central. It's pretty straightforward after having the account set up, basically executing the `uploadArchives` Gradle task.

Let me know if you have any questions or if you need any further information/clarification on the changes made.

cc @raulraja

### CODE REVIEW

**Comment by Guardiola31337** [comment]
> Previous mechanism to build the project (Ant) is still working

If we want to still support Ant, pretty sure we should fix the `build.xml` file and maybe something included in `.externalToolBuilders` (didn't touch nothing there). Could you verify @macroing?

**Comment by Guardiola31337** [comment]
Please add/change/commit anything I might have missed :wink:

**Comment by pakoito** [comment]
@macroing is there anything we can do to help? I have time this week to work on whatever to unlock Arrow's 0.7.X release :D

**Comment by pakoito** [comment]
Thank you much, really appreciated 🎉

**Comment by macroing** [comment]
@Guardiola31337 Thanks for the pull request!

I have merged the pull request and changed some parts of it. One of them is the build.xml file itself for Apache Ant to work. It's now possible to build the project with Apache Ant. The Evaluate.png file is used in a relative way, using GUI.class.getResource(...).

You may have to check that Gradle and Maven still works as well.

@pakoito Thanks for offering help! One thing I'm interested to hear about, is if you have any ideas for new features to add?

**Comment by pakoito** [comment]
Would it be possible to have some form of global configuration to have some external packages preloaded alongside the current ones? Our context of use for the engine is [doc snipped validation](https://github.com/arrow-kt/ank) against libraries, so having them configured as imported by default in our gradle plugin in a way that we can forward it to CEL4J would make our life so much easier!!

**Comment by Guardiola31337** [comment]
@macroing 
> I have merged the pull request

Awesome! Thanks a lot 😊

> You may have to check that Gradle and Maven still works as well.

Sure thing. I'll keep you posted.

> One thing I'm interested to hear about, is if you have any ideas for new features to add?

As commented [here](https://github.com/macroing/CEL4J-Artifact/issues/1#issuecomment-375893323) I will follow with some questions that showed up after testing _Artifact_ as ScriptEngine for the Java code in [ΛNK](https://github.com/arrow-kt/ank) locally.

> After merging this PR I can guide you on how to create a [Bintray account](https://bintray.com/signup/oss) and how to upload the artifact to Bintray and Maven Central.

@macroing did you have a chance to create the Bintray account? How can I contact you so I can explain you next steps to move forward on making the CEL4J-Artifact release available in `jcenter` and `mavenCentral`? Email? Hangouts?

**Comment by macroing** [comment]
@pakoito That sounds like a great idea!

What do you think about having to specify a system property that points to a file with one import statement per line? Something like the following...

``java -Dorg.macroing.cel4j.artifact.import="path/to/import-file.txt" -jar org.macroing.cel4j.artifact.jar``

@Guardiola31337 You're welcome!

I'll make sure to check for your questions on that issue page.

I just created a Bintray account. My username there is macroing. You can contact me via e-mail. My e-mail address is joergen.lundgren@macroing.org.

**Comment by pakoito** [comment]
@macroing I had in mind something that was available at runtime, like:

```
public class HelloWorld {
    public static void main(String[] args) {
        try {
            Cel4J.preload("com.my.lib.*", "com.my.lib.internal.*");

            ScriptEngineManager scriptEngineManager = new ScriptEngineManager();
            ScriptEngine scriptEngine = scriptEngineManager.getEngineByExtension("java");

            scriptEngine.eval("MyLibInternal.function(1)");
        } catch(ScriptException e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by macroing** [comment]
@pakoito Okay I understand. I added support for that too just now.

`Artifact.addGlobalImportStatements("import com.my.lib.*;", "import com.my.lib.internal.*;");`

**Comment by Guardiola31337** [comment]
> I just created a Bintray account. My username there is macroing. You can contact me via e-mail. My e-mail address is joergen.lundgren@macroing.org.

I sent you follow instructions by email. Let me know if you have any questions. Thanks again @macroing

**Pull request merged**
